config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users do
    collection do
      get 'new_session'
      post 'create_session'
      delete 'destroy_session'
    end
  end

  resources :events do
    member do
      post 'register'
    end
  end
  root 'users#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_attendees
  has_many :attendees, through: :event_attendees
  belongs_to :creator, class_name: 'User'
  has_one_attached :event_image

  scope :past, -> { where('event_date < ?', Time.now) }
  scope :upcomming, -> { where('event_date > ?', Time.now) }

  validates :event_name, presence: true
  validates :event_place, presence: true
  validates :event_date, presence: true
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: :user_id
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :event_attendees
  has_many :events, through: :event_attendees
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_one_attached :avatar

  validates :username, presence: true, uniqueness: { case_sensitive: true }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze }
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params.merge(creator_id: session[:user_id]))
    if @event.save
      redirect_to user_path(session[:user_id])
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def register
    EventAttendee.create(event_id: params[:id], user_id: session[:user_id])
    flash[:notice] = 'Hello'
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :event_place, :event_date, :creator_id, :event_image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  @error = nil
  before_action :check_session, only: %i[show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_users_path
    else
      render 'new'
    end
  end

  def show
    @events = helpers.current_user.created_events
  end

  def new_session; end

  def create_session
    c_user = User.find_by(username: params['username'])
    if c_user.nil?
      @error = "User name doesn't exists"
      render 'new_session'
    else
      session[:user_id] = c_user.id
      redirect_to user_path(c_user.id)
    end
  end

  def destroy_session
    session[:user_id] = nil
    redirect_to new_session_users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :username, :last_name, :email, :avatar)
  end

  def check_session
    redirect_to new_session_users_path if session[:user_id].nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    return nil if session[:user_id].nil?

    User.find(session[:user_id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts = {}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<div class="hero-bg past-upcomming index-p">
    <% if @events.past.empty? && @events.upcomming.empty? %>
    <p>No Events Found</p>
    <% else %>
    <% if !(@events.past.empty?) %>
        <h2>Past Events</h2>
        <table class="table table-hover">
        <tr>
        <th>Event Name</th>
        <th>Event Place</th>
        <th>Event Date</th>
        <th>Details</th>
        </tr>
        <% @events.past.each do |e|%>
        <tr>
        <td><%= e.event_name %></td>
        <td><%= e.event_place %></td>
        <td><%= e.event_date %></td>
        <td class="det"><%= link_to 'Details', event_path(e.id) %></td>
        </tr>
        <%end%>

        </table>
    <% end %>
    <% if !(@events.upcomming.empty?) %>
        <h2>Upcomming Events</h2>
        <table class="table table-hover text-white">
        <tr>
        <th>Event Name</th>
        <th>Event Place</th>
        <th>Event Date</th>
        <th>Details</th>
        </tr>
        <% @events.upcomming.each do |e|%>
        <tr>
        <td><%= e.event_name %></td>
        <td><%= e.event_place %></td>
        <td><%= e.event_date %></td>
        <td class="det"><%= link_to 'Details', event_path(e.id) %></td>
        </tr>
        <%end%>
        </table>
        <% end %>
    <% end %>
</div>

app/views/events/new.html.erb
<div class="hero-bg">
<div class="main d-flex justify-content-center align-items-center flex-column">
<h2 class="styled-h2">Create an Event</h2>
<%= form_with model:@event, class: 'form py-5 pl-5', id: 'event-form' do |f|%> 
  <%= label_tag(:event_name, "Event Name", class: "") %>
  <%= f.text_field :event_name, class: "ml-5" %>
  <br/>
  <%= label_tag(:event_place, "Event Location", class: "") %>
  <%= f.text_field :event_place, class: "event-place" %>
  <br/>
  <%= label_tag(:event_date, "Event Date", class: "") %>
  <%= datetime_local_field(:event, :event_date, class: "date-time") %>
  <br/>
  <%= label_tag(:event_image, "Choose event image", class: "") %>
  <%= f.file_field :event_image %>
  <br/>
  <%= f.submit "Create Event", class: "btn btn-success login-btn" %>
<% end %>
</div>
</div>

app/views/events/show.html.erb
<div class="container-fluid demo past-upcomming">
<div class="content">
<div class="large-header">
<h2 class="styled-h2">Event Details</h2>
<table class="table table-hover text-white table-white">
    <tr>
        <th>Event Name</th>
        <th>Event Place</th>
        <th>Event Date</th>
        <th>Event Poster</th>
    </tr>
    <tr>
        <td><%= @event.event_name %></td>
        <td><%= @event.event_place %></td>
        <td><%= @event.event_date %></td>
        <td><%= link_to  image_tag(url_for(@event.event_image)), url_for(@event.event_image), target: :_blank %>
        </td>
    </tr>
</table>
<%= button_to 'Rigester Now', register_event_path(@event.id), class: "register-btn " %>
<h2 class="styled-h2">Creator</h2>
<table class="table table-hover table-white">
    <tr>
        <th class="texr-white">Name</th>
        <th>Creator's Email</th>
        <th>Creator's Photo</th>
    </tr>
    <tr>
        <td><%= @event.creator.first_name %>
        <%= @event.creator.last_name %>
        </td>
        <td><%= @event.creator.email %></td>
        <td><%= link_to  image_tag(url_for(@event.creator.avatar)), url_for(@event.creator.avatar), target: :_blank %>
        </td>
    </tr>
</table>
<h2 class="styled-h2">Event Attendees</h2>
<table class="table table-hover">
    <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    </tr>
    <% @event.attendees.each do |e|%>
    <tr>
    <td><%= e.first_name %></td>
    <td><%= e.last_name %></td>
    <td><%= e.email %></td>
    </tr>
<%end%>

</table>
</div>
</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav w-100">
      <li class="nav-item active">
      <%= link_to 'Home', user_path(session[:user_id]), class: 'nav-link'  %>
      </li>
      <li class="nav-item">
        <%= link_to 'Create Event', new_event_path(session[:user_id]), class: 'nav-link'  %>
      </li>
      <li class="nav-item">
        <%= link_to 'All Events', events_path, class: 'nav-link'  %>
      </li>
      <li class="nav-item ml-auto">
        <%= link_to 'Log out', destroy_session_users_path, :method => 'delete', class: 'nav-link'  %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if !current_user.nil? %>
    <%= render partial: '/layouts/navbar' %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/user/signup.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <h2>Sign Up</h2>
    <%= form_for @user do |f| %>
      <%= form_group_for f, :username, label: false  do %>
        <div class="input-group">
          User Name: <%= f.text_field :username, class: 'form-control', placeholder: 'UserName' %>
        </div>
      <% end %>
      <%= form_group_for f, :firstname, label: false  do %>
        <div class="input-group">
          First Name: <%= f.text_field :firstname, class: 'form-control', placeholder: 'first name' %>
        </div>
      <% end %>
      <%= form_group_for f, :lastname, label: false  do %>
        <div class="input-group">
          Last Name: <%= f.text_field :lastname, class: 'form-control', placeholder: 'last name' %>
        </div>
      <% end %>
      <%= form_group_for f, :email, label: false  do %>
        <div class="input-group">
          Email    : <%= f.text_field :email, class: 'form-control', placeholder: 'example@email.com' %>
        </div>
      <% end %>                  
      <%= f.submit("Create User", class:"btn btn-primary", data: {:confirm => msg('Do you want to create user?'), :disable_with => 'Creating'}) %>
    <% end %>
  </div>    
</div>

app/views/users/new.html.erb
<div class="hero-bg">
<div class="main d-flex justify-content-center align-items-center flex-column">
<h2 class="styled-h2">Sign up</h2>
<div class= "form">
<%= form_with model: @user, class: 'form py-5 pl-5', id: 'test_signup' do |f| %>
  <%= label_tag(:username, "Username", class: 'm-2') %>
  <%= f.text_field :username, class: 'ml-1' %>
  <br/>
  <%= label_tag(:first_name, "First Name", class: 'm-2') %>
  <%= f.text_field :first_name %>
  <br/>
  <%= label_tag(:last_name, "Last Name", class: 'm-2') %>
  <%= f.text_field :last_name %>
  <br/>
  <%= label_tag(:email, "Email", class: 'email_tag') %>
  <%= f.email_field :email, class: 'email'%>
  <br/>
  <%= label_tag(:avatar, "Choose Image", class: 'ml-2 mt-2') %>
  <%= f.file_field :avatar %>
  <br/>
  <div class="d-flex flex-row align-items-center pr-2">
        <%= f.submit "Sign Up", class: "login-btn btn btn-success mb-1" %>
        <p class="ml-2 mt-4 mr-2">or</p>
        <%= link_to 'Log in', new_session_users_path, class: "mt-2 font-weight-bold" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/users/new_session.html.erb
<div class="hero-bg">
  <div class="main d-flex justify-content-center align-items-center flex-column">
    <h2 class="styled-h2">Log in </h2>
    <br>
    <div class= "form", id="test">
    <%= form_with( url: create_session_users_path ,class: 'form') do |f| %>
      <%= label :username, "username ", class: 'm-5' %>
      <%= f.text_field :username, placeholder: 'username', class: 'mr-5' %>
      <br/>
      
      <div class="d-flex flex-row align-items-center pr-2">
        <%= f.submit ("Sign in"), class: 'login-btn mb-3 btn-success btn' %>
        <p class="ml-2 mt-3 mr-2">or</p>
        <%= link_to 'Sign Up', new_user_path %>
      </div>
    <% end %>
        <% unless @error.nil? %>
          <p class="text-dark">
            <%= @error.inspect %>
          </p>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid demo past-upcomming">
<div class="content">
<div class="large-header">
<% if !@events.empty? %>
<h2 class="text-light">User Created Events</h2>
<table class="table table-hover">
  <tr>
    <th>Event Name</th>
    <th>Event Place</th>
    <th>Event Time</th>
    <th>Register</th>
  </tr>
  <% @events.each do |e| %>
    <tr>
      <td>
        <%= e.event_name %>
      </td>
      <td>
        <%= e.event_place %>
      </td>
      <td>
        <%= e.event_date %>
      </td>
      <td>
        <%= e.event_date %>
      </td>
    </tr>
  <% end %>
</table>
<% end %>
<% if current_user.events.past.empty? && current_user.events.upcomming.empty?%>
<h2 class="text-light">Registered Events</h2>
<p class="text-light">No Registered Events Found</p>
<% end %>
<% if !(current_user.events.past.empty?) %>
  <h3>Previously Attended Events</h3>
  <table class="table table-hover">
    <tr>
      <th>Event Name</th>
      <th>Event Place</th>
      <th>Event Time</th>
    </tr>
    <% current_user.events.past.each do |e| %>
        <tr>
          <td>
            <%= e.event_name %>
          </td>
          <td>
            <%= e.event_place %>
          </td>
          <td>
            <%= e.event_date %>
          </td>
        </tr>
    <% end %>
  </table>
<% end %>
<% if !(current_user.events.upcomming.empty?) %>
<h2 class="text-light">Upcoming Events</h2>
<table class="table table-hover">
  <tr>
    <th>Event Name</th>
    <th>Event Place</th>
    <th>Event Time</th>
  </tr>
  <% current_user.events.upcomming.each do |e| %>
      <tr>
        <td>
          <%= e.event_name %>
        </td>
        <td>
          <%= e.event_place %>
        </td>
        <td>
          <%= e.event_date %>
        </td>
      </tr>
    
  <% end %>
</table>
<% end %>
</div>
</div>
</div>